name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      working-directory: ./Forte.React.AspNetCore
      run: dotnet build -c Release
    - name: Pack nugets
      working-directory: ./Forte.React.AspNetCore
      run: dotnet pack -c Release --no-build --output . 
    - name: Push to NuGet
      working-directory: ./Forte.React.AspNetCore
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json